---
title: "CURRICULUM VITAE"
author: "Kostadin Rangelov Kostadinov, MD, MPH, MEcon"
format:
 pdf:
  mainfont:  "Sofia Sans Condensed Light"
  sansfont:  "Sofia Sans Condensed Light"
  monofont:  "Sofia Sans Condensed Light"
  fontsize: 12pt
---

[drkostadinkostadinov@gmail](https://drkostadinkostadinov@gmail.com) \| [GitHub](https://github.com/kostadinoff) \| [Twitter](https://twitter.com/kostadinoffMD) \| [Linkedin](https://linkedin.com/in/kostadinovmd) \| [ORCID](https://orcid.org/0000-0003-1414-8738)


# Personal data

`Date of birth`

- 1992-04-01
- Plovdiv, Bulgaria 

---

# Education

`10/2021-09/2022`

- Master of Economics and Finance
- Sofia University "Kliment Ohridski", Faculty of Economics 

`10/2017-09/2019`

- Master of Public Health and Health Management
- MU-Plovdiv, Faculty of Public Health

`09/2012-12/2017`

- Master's degree in Medicine
- Medical university - Plovdiv, Faculty of Medicine

--- 
   
# Work experience

`09/2021-present`

- Medical university - Plovdiv
- Assistant
- Teaching and practical classes in the disciplines of medical ethics; biostatistics; social medicine and public dental health.

`12/2020-present`

- Clinic "Medicus Alpha
- Health. Inpatient and outpatient care
- Physician coordinator
- Diagnostic and therapeutic activity in the field of internal medicine and cardiology.

`12/2017-03/2020`.

- University Hospital "Plovdiv"
- Healthcare. Hospital care
- Specialist doctor
- Diagnostic and therapeutic activity in the field of internal medicine and cardiology.


## Participation in NGOs

`2021 - present`

- Doctors Network "Air for Health" Association

`2013 - present`

- "European Network for Creativity and Innovation" Association
	
`2011-2017`

- Student Council President, President of the GA

`2012-2017`

- Association of Medical Students in Bulgaria Chairman of the Control Council. Secretary

---

# Personal skills and competences

## Teaching

Teaching in the disciplines of medical ethics; biostatistics; social medicine and public dental health. 

## Language

`Bulgarian`	

- Native

`English`

-  First Certificate in English (FCE) - Cambridge English Language Assessment 
      - Reading C1
      - Writing B2
      - Use of English C1
      - Listening B2
      - Speaking C1

## Social

Academic and teaching activities in a multicultural environment with medical and dental students. Postgraduate courses with participants from all continents. Active participation in social and philanthropic projects of non-profit and non-governmental organizations. Additional professional training in Ireland, Austria, Finland. 

## Computer skills

`Programming languages and tools`

- *Data analysis*
    **R**; Python; SPSS; SAS; STATA
    
- *Data mining*
    **Orange**; SPSS Modeler
    
- *Data presentation*
    **R**; Tableau; RAW; PowerBI 
     
- *Other*
    Linux; R studio; MySQL; Latex; VS code; Quarto; Pandoc; Microsoft 365; Google Workspace; Git; GitHub; Markdown; HTML; CSS.

## Other

- Driving license

# Membership in professional organizations

## National

`2016` Youth Scientific Society "Asclepius"

`2017` Bulgarian Medical Association

`2017` Society of Cardiologists in Bulgaria

`2020` Bulgarian Scientific Society of Public Health

`2020` Bulgarian Public Health Association

`2016` Association of trainers and researchers in general medicine in Bulgaria

`2020` Association for Social Research and Applied Research Practices

## International

`2020` European Public Health Association

`2022` World Federation of Public Health Associations (WFPHA)

---

# Publications

## Abstracts in English language

- Raycheva, R., and **K. Kostadinov**. “HTA69 Delay of Innovative Oncology Treatments - Case From Bulgaria.” Value in Health, vol. 25, no. 12, Supplement, Dec. 2022, pp. S309–10. ScienceDirect, https://doi.org/10.1016/j.jval.2022.09.1529.

- Raycheva, R, and **K Kostadinov**. “HTA69 Delay of Innovative Oncology Treatments - Case From Bulgaria.” Value in Health, ISPOR Europe 2022 Abstracts, 25, no. 12, Supplement (December 1, 2022): S309–10. https://doi.org/10.1016/j.jval.2022.09.1529

## Full-text articles in English language

- Peter Kelly, Mohamad M. Saab, Emma J. Hurley, Sinéad Heffernan, John Goodwin, Zamzaliza A. Mulud, Maria O Malley, James O Mahony, Margaret Curtin, Gunter Groen, Svetla Ivanova, Astrid Jörns-Presentati, Joonas Korhonen, **Kostadin Kostadinov**, Mari Lahti, Valentina Lalova, Gergana Petrova & Aine O Donovan. "Trauma Informed Interventions to Reduce Seclusion, Restraint and Restrictive Practices Amongst Staff Caring for Children and Adolescents with Challenging Behaviours: A Systematic Review. Journ. Child Adol. Trauma (2023)". <https://doi.org/10.1007/s40653-023-00524-2>

- Ignatova, Valentina, **Kostadin Kostadinov**, Evguenia Vassileva, Naira Muradyan, Georgi Stefanov, Georgi Iskrov, and Rumen Stefanov. "Socio-Economic Burden of Myasthenia Gravis: A Cost-of-Illness Study in Bulgaria". Frontiers in Public Health <https://doi.org/10.3389/fpubh.2022.822909>

- F. Kiani, **K. Kostadinov**, R. . Stefanov, and V. Mandova, "Dentophobia-latent Component Factor Analysis of Dental Concerns Assessment Scale," Open Access Maced J Med Sci, vol. 11, no. E, pp. 53-58, Jan. 2023. <https://doi.org/10.3889/oamjms.2023.9749>, eISSN: 1857-9655

## Full-text articles in Bulgarian language

- Khubenova, M, **Kostadinov K**., "[Change in dietary habits during the anti-epidemic measures on the occasion of COVID-19"](https://cml.mu-sofia.bg/CML/assets/files/OM-1-2022-%D0%9A%D0%BE%D1%81%D1%82%D0%B0%D0%B4%D0%B8%D0%BD%20%D0%9A%D0%BE%D1%81%D1%82%D0%B0%D0%B4%D0%B8%D0%BD%D0%BE%D0%B2.pdf). journal. "General Medicine" no. 24, 2020; 23-29.

- **Kostadinov, K.**, Stefanov, G., Iskrov, G. & Stefanov, R. Epidemiology of acquired thrombotic thrombocytopenic purpura. Rare Diseases and Orphan Drugs 11, 36-44 (2020).  Rare Diseases and Orphan Drugs, vol. 11, no. 3, Oct. 2020, pp. 36-44, <https://doi.org/10.36865/2020.v11i3.122>.


## Full-text articles in Bulgarian in scientific proceedings

- Ivan Atanasov, Venelina Dudulova, Gina Stoykova, Gergana Lengerova, **Kostadin Kostadinov**, Eleonora Hristova, Georgi Iskrov, Rumen Stefanov" Quality of life in South central region of Bulgaria - preliminary results by employment status from an EQ-5D study" Varna Medical Forum, Black sea Symposium for young scientists in biomedicine 2016 vol.5, no.1.

- **Kostadinov K.**, Stefanova M., Delcheva G. Maneva, A. ["Molecular mechanisms of endoplasmic stress"](https://asclepius.bg/cnm/wp-content/uploads/2022/05/mnd_2013.pdf) Proc. "Science and Youth, 2013, 327-340, ISSN 1314-9229

- Е. Tsvetkov, **K. Kostadinov** ["Survey of sexual culture and education among high school students"](https://asclepius.bg/cnm/wp-content/uploads/2022/05/mnd_2013.pdf) Sb. "Science and Youth, 2013, ISSN 1314-9229

- Elizar Tsvetkov, **Kostadin Kostadinov**, Dancho Gurdev ["Side effects of treatment of rheumatoid arthritis with cortisone drugs"](https://asclepius.bg/cnm/wp-content/uploads/2022/05/sbornik-2014.pdf) Sb. "Science and Youth, 2014, ISSN 1314-9229

- П. Selimov, R. Karalilova, I. Yakov, M. Geneva, A. Batalov, V. Popova, S. Terziyska, L. Stoyanova, M. Karagyozov, D. Gurdev, E. Tsvetkov, **K. Kostadinov** ["Tophi in the hands and feet in chronic gout - a complication worsening the quality of life in affected patients](https://asclepius.bg/cnm/wp-content/uploads/2022/05/sbornik-2014.pdf) Coll. "Science and Youth, 2014, ISSN 1314-9229

- **Kostadin Kostadinov** , Elizar Tsvetkov, Niki Gurdev ["Therapeutic strategies in the treatment of type II diabetes mellitus"](https://asclepius.bg/cnm/wp-content/uploads/2022/05/sbornik-2014.pdf) Sb. "Science and Youth, 2014, ISSN 1314-9229

- **Kostadinov, K.** Tsvetkov, E. Yankov, I. Eosinofic esophagitis - is the incidence of disease really increased in children? March 2016 2-nd National conference of Young Gastroenterologists, University Hospital "Tsariza Yoana", Sofia

- Eleonora Hristova,Ivan Atanasov, Venelina Dudulova, Gergana Lengerova, **Kostadin Kostadinov**, Georgi Iskrov , Rumen Stefanov ["Quality of life in the Southwest region - preliminary results by sex and age from a representative survey with EQ-5D"](https://asclepius.bg/cnm/wp-content/uploads/2022/05/Sbornik-nauka-i-mladost-2016.pdf) Coll. "Science and Youth, 2016, ISSN 1314-9229

- **Kostadinov, K.** Tsvetkov, E. Yankov, I. Cerebral palsy associated with Cystic Fibrosis- RBLS, R. (2019). 9th National Conference on Rare Diseases and Orphan Drugs - Proceedings of presentations and posters. Rare Diseases and Orphan Drugs, 9(2). <https://doi.org/10.36865/2018.v9i2.93>

- **Kostadinov K**, Kehayov D, Tsvetkov E, Kondareva R, Havalyova A, Hristova E. Vegener granulomatosis- clinical aspects, diagnosis and pathomorphology. RBLS, R. (2019). 6th National Conference on Rare Diseases and Orphan Drugs - Proceedings. Rare diseases and orphan drugs, 6(1). <https://doi.org

---

# Project activity

## National projects

`31/10/2013` 

- Project BG05PO001-3.3.07-0002 "Student Practices"

`09/2015` 

- K-Trio/ contract 633175 "Night of the Scientists" 2015.

`04/2021` 

- National scientific program "Young scientists and postdoctoral fellows" P-322/08.03.2021

`09/2021` 

- "Rapid microbiological diagnosis of genital infections in women and men - comparative analysis" № NO-03/2020 (NO-P-8445) . Research project funded under the Regulation of the Ministry of Education and Science of 01.01.2017 on the conditions and procedure for planning, allocation and spending of funds earmarked from the state budget for the scientific or artistic-creative activities inherent to higher education institutions.

`09/2022` 

- "Antimicrobial activity of canal filling agents for the treatment of endodontic infection of temporary teeth" PhD and postdoctoral projects DPDP 04/01.09.2021
- 
## International projects


`3-15/09/2012`

- Nuclear Pharmacy Integrated Course for Students in Pharmacy, Medicine, Medical Physics and Nuclear Chemistry (NuPhICos).Logistics assistant Erasmus Intensive Program Project 2012-1-BG-ERA10-07058

`28/09/2012`

- IN CLOSE- INNOVATIONS "New Composers and Opportunities for Sustainable Development" FP7-CSA-2012-316611, FP7-PEOPLE-2012-RESEARCHERS' NIGHT

`1-9/09/2013`

- ITC "ACCESS-INCLUSION-GROUGHT" Youth in Action, EU, Greece

`3-17/11/2013`

- Nuclear Pharmacy Integrated Course for Students in Pharmacy, Medicine, Medical Physics and Nuclear Chemistry (NuPhICos).Active participant. Erasmus Intensive Program Project 2013-1-BG-ERA10-00320

`06-08/09/2014`

- European Medical Students Congress "Rare diseases and orphan Drugs", Plovdiv

`02/2020`

- Promoters of advanced oncogenetics open online training and multimedia raise awareness on multidisciplinary assessment of patients and their families at risk of hereditary or familial cancerHOPE How Oncogenetics Predicts & Educates Erasmus+ program.2018-1-RO01-KA202-049189

`06-08/09/2014`

-   European Medical Students Congress "Rare diseases and orphan Drugs", Plovdiv

`03/2020-05/2020`

- "Interdisciplinarity, multiculturalism and patient handling in non-standard situation in the context of didactic activities in the field of medical sciences and health sciences in Simulation Medical Centres" project No. 2019-1-PL01-KA203-065205 under the Erasmus Programme. Key Action 2: Cooperation for innovation and the exchange of good practices KA 203: Strategic partnerships for higher education

`09/021`

- Screen4Care - Shortening the path to rare disease diagnosis by using newborn genetic screening and digital technologies- the Innovative Medicines Initiative 2 Joint Undertaking (JU) under grant agreement No 101034427.

`02/2022`

- Caring violent child safely in child psychiatric and residential units under the Erasmus+ Programme, Key Action 2; Agreement number: 2021-1-FI01-KA220-HED-000032106

`04/2023`

- Developing multi-professional Higher Education for promoting mental health and well-being at schools Project Reference: 2020-1-FI01-KA203-066521

## Clinical trials

`2018-2019`

- ApoA-I Event reducinG in Ischemic Syndromes II (AEGIS II); Study Coordinator

---

# Participation in congresses

## National

`27-29/09/2019`

- 11th scientific meeting-training of SOIBOM "The way of the patient with cardiovascular diseases" Oral presentation "Clinical case of valvular atrial fibrillation" **K.Kostadinov**

`28/11/2020`

- Virtual Congress Center "Rare Diseases and Orphan Drugs" ["Acquired Thrombotic Thrombocytopenic Purpura on the Path of Challenges"](https://youtu.be/R_UbvDcyTxs) **K.Kostadinov**

`09-11/03/2021`

- Science and Youth 2021 Conference 

1. "Changing dietary habits and behaviour during the anti-epidemic measures imposed on the occasion of COVID 19". Oral presentation. M. **Kostadinov K.** Mandova V. (lecture)

2. "Change in physical activity in the context of anti-epidemic measures" Oral presentation **Kostadinov K.** Khubenova M. Mandova V. (lecture)

3. ["Oral health self-assessment among haemophilia families"](https://asclepius.bg/cnm/wp-content/uploads/2022/05/Sbornik-Nauka-i-Mladost-2021.pdf) Victoria Mandova, **Kostadin Kostadinov**, Rumen Stefanov

`13-14/05/2021`

- XIVth National Scientific and Technical Conference with foreign participation "Ecology and Health"

1. ["Contemporary microbiological and molecular biological screening of genital infections in symptomatic non-pregnant women"](https://hst.bg/ECOLOGY%20AND%20HEALTH%202021.pdf) Eli Hristozova, Zoya Rachkovska, Tihomir Dermendzhiev, Mariana Murdjeva, Vida Georgieva, Ekaterina Uchikova, **Kostadin Kostadinov** - MU Plovdiv"

`14-16/09/2021`

- XVIII National Congress on Clinical Microbiology and Infections of the Bulgarian Association of Microbiologists " Rapid molecular biological screening for vaginal candidiasis in symptomatic women" Hristozova E., Rachkovska , Georgieva V., Dermendzhiev T., **Kostadinov K.**, Vlahova M., Uchikova E. , Murdjeva M. (poster)

`15-16/09/2022`

- XX Jubilee National Congress on Clinical Microbiology and Infections of the Bulgarian Association of Microbiologists

1. ["Investigation of the urethral microbiome with androflor screen in men with nonspecific genital symptoms in a covid-19 pandemic setting"](https://www.bam-bg.net/images/documents/3Posters.pdf) E. Hristozova, T. Dermendzhiev, Z. Raczkowska, V. Georgieva, **K. Kostadinov**, Ts. Pavlov, M. Murdjeva (incl. in the Proceedings) 

2. ["Omicron - reassurance or challenge?"](https://www.bam-bg.net/images/documents/2Abstracts.pdf) M. Atanasova, N. Korsun, R. Komitova, **K. Kostadinov**, I. Alexiev, R. Raicheva, I. Ivanov, L. Petkova, L. Joglova (incl. in Proceedings) 

`30/09/2022-01/10/2022`

- Fourth National Conference on Epidemiology. "Infectious Diseases in Bulgaria- Problems and Perspectives" theme" "CauVID-19 in Bulgaria and the impact of vaccines on hospitalization, mortality and lethality A. Kevorkian, **K. Kostadinov**, V. K. A. Kunchev, A. Serbezova

`16/12/2022`

- Effects of DCEA as a streoid precursor on immunological reactivity in different occupational groups in distress. Maria Ivanovska, Petya Angelova Gardzheva, Dora Dimitrova Terzieva, Nonka Georgieva Mateva, **Kostadin Rangelov Kostadinov**, Teodora Mitkova Kalfova , Mariana Atanasova Murdzheva (poster-paper). Annual Scientific Conference on Immunology, Bulgarian Association of Clinical Immunology.

## International

`20-23/10/2022`

- Joint Forum: 12th South-East European Conference and 32nd Annual Assembly of IMAB.  "Antimicrobical activity of root canal filling materials for endodonic treatment in primary dentition" Maria Shindova, Eli Hristozova, Plamen Katsarov, Michael Onov, **Kostadin Kostadinov**, Vasko Toplev, Ani Belcheva

`6-9/11/2022`

- [Delay of Innovative Oncology Treatments - Case From Bulgaria](https://www.ispor.org/heor-resources/presentations-database/presentation/euro2022-3565/120960), Poster session, Raycheva R,**Kostadinov K**; 2022-11, ISPOR Europe 2022, Vienna, Austria; Value in Health, Volume 25, Issue 12S (December 2022)

`15-8/04/2023`

- 33-rd European Congress of Clinical Microbiology and Infectious Diseases" Impact of COVID-19 vaccines -data from Bulgaria" Ani Kevorkyan, **Kostadin Kostadinov**, Vania Rangelova, Ralitsa Raycheva , Angel Kunchev

`4-11/03/2023`

- Immunological reactivity under acute and chronic stress. Where are we? Experience in Bulgaria. M. Ivanovska, T. Kalfova, P. Gardva, **K. Kostadinov**, M. Murdjeva

`8-10/05/2023`

- [The Price of Innovation - Oncology Treatments Expenditures: Case from Bulgaria](https://www.ispor.org/docs/default-source/intl2023/ispor23raychevaposter-pdf.pdf?sfvrsn=d7fc52be_0), Poster session, Raycheva R,**Kostadinov K**; 2023-05, ISPOR 2023, Boston, MA, USA; Value in Health, Volume 26, Issue 6 (June 2023)

---

# Training & Califications

## National trainings

`24-25/09/2011`

- Medical University Plovdiv "Emergency Care in Medicine" NO-17/2011 gr. Plovdiv 22-23. november. 2012. National Program for Prevention and Control of HIV and Sexually Transmitted Infections in the Republic of Bulgaria 2008-2015 "Treatment and Care for People Living with HIV/AIDS and Reducing Stigma and Discrimination" gr. Plovdiv

`16/12/2012`

- Tokuda Hospital Sofia "Basic surgical skills"

`20-21/10/2014`

- Programme funded by the Global Fund to Fight AIDS, Tuberculosis and Malaria "Diagnosis, care and treatment of people living with HIV/AIDS (PLWHA) for the needs of the PFGF" gr. Plovdiv

`24-28/04/2017`

- National Institute of Radiobiology and Radiation Protection "Medical support in radiation, nuclear accidents and terrorism emergency preparedness" gr. Sofia

`15-17/07/2018`

- Scientific Symposium "Acute Coronary Syndrome" gr. Plovdiv

`7-9/11/2019`

- Scientific Symposium "Tachyarrhythmias and Syncope" 22-23 November 2019. 3rd School of Echocardiography. "New echographic methods in cardiology".

`1-2/12/2022`.

- Final conference of the National National Program "Electronic Healthcare in Bulgaria"

## International trainings

`1-2/12/2017`

- Critical appraisal course, gr. Sofia CPD

`27/03/2021`

- 8th annual symposium "HTA assessment -- strategies for accelerated access" Institute for Rare Diseases

`10-15/10/2022`

- Orep Medical Institute (OMI) Seminar "Economic Evaluation in Healthcare"

## Classifications

`10/11/2017`

- National Heart Hospital "Echocardiographic Assessment of Cardiac Function"

`19-20/10/2018`

- First School of Echocardiography. gr. Introduction to echocardiographic diagnostics

`22-23/02/2019 `

- Second school of echocardiography gr. Sofia Echocardiographic evaluation of congenital and acquired cardiovascular diseases

`22-26/03/2021 `

- Course "Biostatistics with IBM SPSS Statistics for Windows, Version 22.0"

`03/2020`

- English for academic purposes, Irina Mittercheva, PhD; Department of Language Education (DESO), MU-Plovdiv 

- Linguistic Issues of Scientific and Medical Text; Department of Language Education (DESO), MU-Plovdiv, Assoc. Prof. Milieva, Ph.

`06/2021` 

- Intensive specialized course "Academic writing, development of Cochrane systematic reviews" 
 Contract KP - 06-DK1/6 of 29.03.2021 "COVID-19 HUB - Information, innovation and implementation of integrative scientific developments", funded under a competition related to the pandemic of COVID-19, at the Fund "Scientific Research" - MES. 

`09/2021`

- "Machine Learning" Machine Learning course; SoftUni
