---
title: "Автобиография"
author: "Костадин Рангелов Костадинов"
format:
 pdf:
  mainfont:  "Old Standard TT"
  sansfont:  "Old Standard TT"
  monofont:  "Old Standard TT"
  fontsize: 12pt
---

[drkostadinkostadinov@gmail](https://drkostadinkostadinov@gmail.com) \| [GitHub](https://github.com/kostadinoff) \| [Twitter](https://twitter.com/kostadinoffMD) \| [Linkedin](https://linkedin.com/in/kostadinovmd) \| [ORCID](https://orcid.org/0000-0003-1414-8738)


# Лични данни

`Дата на раждане`

-   1992-04-01
-   гр. Пловдив, България 

# Образование

`октомври 2021-септември 2022 г.`

-   Магистър „Икономика и финанси"
-   Софийски университет "Климент Охридски", Стопански факултет 

`октомври 2017-септември 2019 г.`

-   Магистър „Обществено здраве и здравен мениджмънт"
-   МУ-Пловдив, Факултет по обществено здраве

`септември 2012-декември 2017 г.`

-   Магистър "Медицина"
-   МУ-Пловдив, Медицински факултет
   
   
# Трудов стаж

`септември 2021-до момента`

-   МУ-Пловдив
-   Асистент
-   Учебно-практически занятия по дисциплините медицинска етика; биостатистика; социална медицина и обществено дентално здраве.

`декември 2020-до момента`

-   СБАЛХБ „Медикус Алфа" ЕООД
-   Здравеопазване. Болнична и извънболнична помощ
-   Лекар-ординатор
-   Диагностично-лечебна дейност в областта на вътрешните болести и кардиологията.

`декември 2017-март 2020 г.`

-   УМБАЛ "Пловдив„ АД
-   Здравеопазване. Болнична помощ
-   Лекар специализант
-   Диагностично-лечебна дейност в областта на вътрешните болести и кардиологията.


## Участие в неправителствени организации

`2013 - до момента`

- "Европейска мрежа за креативност и иновации" Сдружение
	
`2011-2017 г.`

-   Студентски съвет Председател, Председател на ОС

`2012-2017 г.`

-   Асоциация на студентите по медицина в България Председател на контролен съвет. Секретар



# Лични умения и компетентности

## Преподавателска дейност

Учебно-практически занятия по дисциплините медицинска етика; биостатистика; социална медицина и обществено дентално здраве. 

## Езикови

`майчин език`

-   Български

`други езици`

Английски език (B2)

-  Удостоверение 083/21.12.2017г., ДЕСО, МУ-Пловдив 
-  Удостоверение 32/26.06.2017г."N & N New School of English" 2021г.


## Социални

Академична и преподавателска дейност в мултикултурна среда със студенти по медицина и дентална медицина. Курсове за следдипломно обучение с участници от всички континенти Активно участие в социални и благотворителни проекти на неправителствени и нестопански организации.

##  Компютърни умения

`Програмни езици и инструменти`

-   Data analysis
    R;Python; SPSS; SAS; STATA
    
-   Data mining
    Orange; SPSS Modeler
    
-   Data presentation
    Tableau; RAW; PowerBI 
     
-   Други
    Linux; R studio; MySQL; Latex; VS code;html; CSS; Markdown; Microsoft 365; Google Workspace

## Други

-   Свидетелство за управление на МПС, кат. В

# Членство в професионални организации

## Национални

`от 2016 г.` Младежко научно дружество „Асклепий"

`от 2017 г.` Български лекарски съюз.

`от 2017 г.` Дружество на кардиолозите в България.

`от 2020 г.` Българско научно дружество по обществено здраве.

`от 2020 г.` Българската асоциация по обществено здраве

`от 2016 г.` Сдружение на обучители и изследователи в България по обща медицина.

`от 2020 г.` Асоциация за социални изследвания и приложни изследователски практики

## Международни

`от 2020 г.` Европейска асоциация по обществено здраве

# Публикации

## Пълнотекстови статии на английски език

-   Ignatova, Valentina, **Kostadin Kostadinov**, Evguenia Vassileva, Naira Muradyan, Georgi Stefanov, Georgi Iskrov, и Rumen Stefanov. „Socio-Economic Burden of Myasthenia Gravis: A Cost-of-Illness Study in Bulgaria“. Frontiers in Public Health <https://doi.org/10.3389/fpubh.2022.822909>

## Пълнотекстови статии на български език

-   Хубенова, М,  **Костадинов К**., "[Промяна в хранителните навици по време на противоепидемичните мерки по повод COVID-19"](https://cml.mu-sofia.bg/CML/assets/files/OM-1-2022-%D0%9A%D0%BE%D1%81%D1%82%D0%B0%D0%B4%D0%B8%D0%BD%20%D0%9A%D0%BE%D1%81%D1%82%D0%B0%D0%B4%D0%B8%D0%BD%D0%BE%D0%B2.pdf). сп. "Обща медицина" бр. 24, 2020г; 23–29.

-   **Костадинов, К.**, Стефанов, Г., Искров, Г. & Стефанов, Р. Епидемиология на придобитата тромботична тромбоцитопенична пурпура. Редки болести и лекарства сираци 11, 36-44 (2020).  Редки болести и лекарства сираци, Vol. 11, no. 3, Oct. 2020, pp. 36-44, <https://doi.org/10.36865/2020.v11i3.122> 


## В научни сборници

-   Ivan Atanasov, Venelina Dudulova, Gina Stoykova, Gergana Lengerova, **Kostadin Kostadinov**, Eleonora Hristova, Georgi Iskrov, Rumen Stefanov" Quality of life in South central region of Bulgaria - preliminary results by employment status from an EQ-5D study" Varna Medical Forum, Black sea Symposium for young scientists in biomedicine 2016 том 5, бр.1.

-   **Костадинов К.**, Стефанова М., Делчева Г. Манева, А. [„Молекулни механизми на ендоплазмения стрес"](https://asclepius.bg/cnm/wp-content/uploads/2022/05/mnd_2013.pdf) Сб. "Наука и младост", 2013, 327-340, ISSN 1314-9229

-   Е. Цветков, **К. Костадинов** ["Анкетно проучване на сексуалната култура и образование сред учениците в гимназиален етап"](https://asclepius.bg/cnm/wp-content/uploads/2022/05/mnd_2013.pdf) Сб. "Наука и младост", 2013, ISSN 1314-9229

-   Елизар Цветков, **Костадин Костадинов**, Данчо Гурдев ["Странични ефекти от лечението на ревматоиден артит с кортизонови препарати"](https://asclepius.bg/cnm/wp-content/uploads/2022/05/sbornik-2014.pdf) Сб. "Наука и младост", 2014, ISSN 1314-9229

-   П. Селимов, Р. Каралилова, И. Яков, М. Генева, А. Баталов, В. Попова ,С. Терзийска, Л. Стоянова, М. Карагьозов, Д. Гурдев, Е. Цветков, **К. Костадинов** ["Тофи в областта на ръцете и ходилата при хронична подагра - компликация влошаваща качеството на живот при засегнатите пациенти](https://asclepius.bg/cnm/wp-content/uploads/2022/05/sbornik-2014.pdf) Сб. "Наука и младост", 2014, ISSN 1314-9229

-   **Костадин Костадинов** , Елизар Цветков, Ники Гурдев ["Терапевтични стратегии при лечението на захарен диабет тип II"](https://asclepius.bg/cnm/wp-content/uploads/2022/05/sbornik-2014.pdf) Сб. "Наука и младост", 2014, ISSN 1314-9229

-   **Костадинов, К.** Цветков, Е. Янков, И. Eosinofic esophagitis - is the incidence of disease really increased in children? Март 2016 2-nd National conference of Young Gastroenterologists, University Hospital "Tsariza Yoana", Sofia

- Елеонора Христова,Иван Атанасов, Венелина Дудулова, Гергана Ленгерова, **Костадин Костадинов**, Георги Искров , Румен Стефанов ["Качество на живот в Югозападен регион – предварителни резултати по пол и възраст от репрезентативно проучване с EQ-5D"](https://asclepius.bg/cnm/wp-content/uploads/2022/05/Sbornik-nauka-i-mladost-2016.pdf) Сб. "Наука и младост", 2016, ISSN 1314-9229

-   **Костадинов, К.** Цветков, Е. Янков, И.Чернодорбно заболяване свързано с Муковисцидоза- РБЛС, Р. (2019). 9-та Национална конференция за редки болести и лекарства сираци - Сборник с презентации и постери. Редки болести и лекарства сираци, 9(2). <https://doi.org/10.36865/2018.v9i2.93>

-   **Костадинов К**, Кехайов Д, Цветков Е, Кондарева Р, Хавальова А, Христова Е. Грануломатоза на вегенер- клинични аспекти, диагностика и патоморфология. РБЛС, Р. (2019). 6-та Национална конференция за редки болести и лекарства сираци - Сборник с резюмета. Редки болести и лекарства сираци, 6(1). <https://doi.org/10.36865/2015.v6i1.92>

-   **Костадинов К**, Кехайов Д, Цветков Е, Кондарева Р, Хавальова А, Христова Е. Екстрапулмонална саркоидоза- клиничен случай на 13-годишно момче. РБЛС, Р. (2019). 6-та Национална конференция за редки болести и лекарства сираци - Сборник с резюмета. Редки болести и лекарства сираци, 6(1). <https://doi.org/10.36865/2015.v6i1.92>

# Проектна дейност

## Национални проекти

`31.октомври.2013 г.` 

-   Проект BG05PO001-3.3.07-0002 „Студентски практики"

`септември.2015 г.` 

-   К-Трио/ договор 633175 „Нощ на учените" 2015г.

`aприл. 2021 г.` 

-   Национална научна програма "Млади учени и постдокторанти" Р-322/08.03.2021

`септември. 2021 г.` 

-   “Бърза микробиологична диагноза на генитални инфекции при жени и мъже – сравнителен анализ” № НО-03/2020 (НО-Р-8445) . Научноизследователски проект, финансиран по Наредба на МОН от 01.01.2017 г. за условията и реда за планиране, разпределение и разходване на средствата, отпускани целево от държавния бюджет за присъщата на висшите училища научна или художествено-творческа дейност.

`септември. 2022 г.` 

- "Антимикробна активност на каналопълнежните средства за лечение на ендодонтска инфекция на временни зъби" Докторантски и постдокторантски проекти ДПДП 04/01.09.2021

## Международни проекти

`февруари 2022 г.`

-   Caring violent child safely in child psychiatric and residential unitsunder  the  Erasmus+  Programme,  Key  Action  2; Agreement number: 2021-1-FI01-KA220-HED-000032106
`септември 2021 г.`

-  Screen4Care - Shortening the path to rare disease diagnosis by using newborn genetic screening and digital technologies- the Innovative Medicines Initiative 2 Joint Undertaking (JU) under grant agreement No 101034427.

`февруари.2020 г.`

-   Promoters of advanced oncogenetics open online training and multimedia raise awareness on multidisciplinary assessment of patients and their families at risk of hereditary or familial cancerHOPE How Oncogenetics Predicts & Educates Erasmus+ program.2018-1-RO01-KA202-049189

`3-15. септември.2012 г.`

-   Nuclear Pharmacy Integrated Course for Students in Pharmacy, Medicine, Medical Physics and Nuclear Chemistry (NuPhICos).Logistics assistant Erasmus Intensive Program Project 2012-1-BG-ERA10-07058

`28.септември.2012 г.`

-   IN CLOSE- ИНОВАЦИИ „Нови компонисти и възможности за устойчиво развитие" FP7-CSA-2012-316611, FP7-PEOPLE-2012-RESEARCHERS' NIGHT

`1-9. септември.2013 г.`

-   ITC "ACCESS-INCLUSION-GROUGHT" Youth in Action, EU, Greece

`3-17. ноември.2013 г.`

-   Nuclear Pharmacy Integrated Course for Students in Pharmacy, Medicine, Medical Physics and Nuclear Chemistry (NuPhICos).Active participant. Erasmus Intensive Program Project 2013-1-BG-ERA10-00320

`06-08. септември.2014 г.`

-   European Medical Students Congress "Rare diseases and orphan Drugs", Plovdiv

`март-май. 2020 г.`

-   „Интердисциплинарност, мултикултурализъм и работа с пациента в нестандартна ситуация в контекста на провеждане на дидактични занимания в областта на медицинските науки и здравните науки в Симулационни медицински центрове" проект № 2019-1-PL01-KA203-065205 по Програма Еразъм. Key Action 2: Cooperation for innovation and the exchange of good practices KA 203: Strategic partnerships for higher education

# Клнични изпитвания

`2018-2019 г.`

-   ApoA-I Event reducinG in Ischemic Syndromes II (AEGIS II); Study Coordinator

# Конгреси & Обучения

## Активно участие

### Национални

`13-14. септември 2013 г.`

-   I Национална конференция по редки болести за студенти по медицина

`11-12. септември. 2015 г.`

-   VI Национална конференция по редки болести и лекарства сираци „Персонализиран подход и иновации в областта на редките болести" гр. Пловдив

`април. 2016 г.`
-   „Мултифасетен поглед върху детското развитие" гр. Пловдив

`9-10. септември. 2016 г.`

-   VII Национална конференция по редки болести и лекарства сираци „Редките заболявания във фокуса на европейските референти мрежи"


`8-10. септември. 2017 г.`

-   8th National conference for rare diseases and 12th Balkan congress of human genetics "Rare diseases- new horizons for scientific research"

`27-29. септември. 2019 г.`

-   11-та научна среща-обучение на СОИБОМ „Пътят на пациента със сърдечно-съдови заболявания" Орална презентация „Клиничен случай на клапно предсърдно мъждене"

`28. ноември.2020 г.`

-   Виртуален конгресен център „Редки болести и лекарства сираци" [„Придобита тромботична тромбоцитопенична пурпура по пътя на предизвикателствата"](https://youtu.be/R_UbvDcyTxs)

`09-11.март.2021 г.`

-   Конференцията Наука и Младост 2021 

1. „Промяна в хранителните навици и поведение по време на противоепидемичните мерки, наложени по повод COVID 19". Орална презентация. Хубенова М. **Костадинов К.** Мандова В. (лекция)

2. „Промяна в физическата активност в условията на противоепидемични мерки" Орална презентация **Костадинов К.** Хубенова М. Мандова В.(лекция)

3. ["Oral health self-assessment among haemophilia families"](https://asclepius.bg/cnm/wp-content/uploads/2022/05/Sbornik-Nauka-i-Mladost-2021.pdf) Victoria Mandova, **Kostadin Kostadinov**, Rumen Stefanov

`13-14.май.2021 г.`

-   XIV-та национална научно-техническа конференция с чуждестранно участие "Екология и здраве"

1. ["Съвременен микробиологичен и молекулно-биологичен скрининг на генитални инфекции при симптоматични небременни жени"](https://hst.bg/ECOLOGY%20AND%20HEALTH%202021.pdf) Ели Христозова, Зоя Рачковска, Тихомир Дерменджиев, Мариана Мурджева, Вида Георгиева, Екатерина Учикова, **Костадин Костадинов** – МУ Пловдив"

`14-16.септември.2021 г.`

-   XVIII хационален конгрес по клинична микробиология и инфекции на българската асоциация на микробиолозите

1. " Бърз молекулно-биологичен скрининг за вагинална кандидоза при симптоматични жени" Христозова Е., Рачковска , Георгиева В., Дерменджиев Т., **Костадинов К.**, Влахова М., Учикова Е. ,Мурджева М. (постер) 

`15-16.септември.2022 г.`

-   XX Юбилеен национален конгрес по клинична микробиология и инфекции на българската асоциация на микробиолозите

1. ["Проучване уретралния микробиом с androflor screen при мъже с неспециф ична генитална симптоматика в условия на covid-19 пандемия"](https://www.bam-bg.net/images/documents/3Posters.pdf) E. Христозова, Т. Дерменджиев, З. Рачковска, В. Георгиева, **К. Костадинов**, Ц. Павлов, М. Мурджева (вкл. в Сборник с научни трудове) 

2. ["Omicron – успокоение или предизвикателство?"](https://www.bam-bg.net/images/documents/2Abstracts.pdf) М. Атанасова, Н. Корсун, Р. Комитова, **К. Костадинов**, И. Алексиев, Р. Райчева, И. Иванов, Л. Гломб, Ц.Петкова, Л. Джоглова (вкл. в Сборник с научни трудове) 

`30.септември-01.октомври.2022 г.`

-   Четвърта национална конференция по епидемиология. „Инфекциозните заболявания в България- проблеми и перспективи”

1. Ковид-19 в България и влияние на ваксините върху хоспитализацията, смъртността и леталитета А. Кеворкян, **К. Костадинов**, В. Рангелова, Р. Райчева, А. Кунчев, А. Сербезова


## Международни

`3-9. август.2015 г.`

-   International Federation of Medical Students' Association (IFMSA) General assembly, Orchid, Macedonia

`ноември.2022 г.`

-    Black Sea Symposium for Young Scientists in Biomedicine Разработка „Quality of life in south central region of Bulgaria-preliminary results by income, age and sex and employment from an EQ-5D STUDY

`април 2016 г.`

- [Delay of Innovative Oncology Treatments - Case From Bulgaria](https://www.ispor.org/heor-resources/presentations-database/presentation/euro2022-3565/120960), Poster session, Raycheva R,**Kostadinov K**; 2022-11, ISPOR Europe 2022, Vienna, Austria; Value in Health, Volume 25, Issue 12S (December 2022)

## Обучения 

### Национални

`24-25. септември. 2011 г.`

-   Медицински университет Пловдив „Спешна помощ в медицината" НО-17/2011 гр. Пловдив 22-23. ноември. 2012г. Национална програма за превенция и контрол на ХИВ и сексуално предавани инфекции в Република България 2008-2015г. „Лечение и грижи за хора, живеещи с ХИВ/СПИН и намаляване на стигмата и дискриминацията" гр. Пловдив

`16.декември.2012 г.`

-   Токуда болница София „Основни хирургически умения"

`05-06. април.2013 г.`

-   Интердисциплинарна конференция

`20-21. октомври. 2014 г.`

-   Програма финансирана от Глобалния фонд за борба срещу СПИН, туберкулоза и малария „Диагностика, грижи и лечение на хора живеещи с ХИВ/СПИН (ХЖХС) за нуждите на ПФГФ" гр. Пловдив

`24-28.април. 2017 г.`

-   Национален институт по радиобиология и радиационна защита „Медицинско осигуряване при радиационни, ядрени аварии и тероризъм аварийна готовност" гр. София

`10.ноември.2017 г.`

-   Национална кардиологична болница „Ехокадиографската оценка на сърдечна функция"

`15-17. юли 2018 г.`

-   Научен симпозиум „Остър коронарен синдром" гр. Пловдив

`19-20. октомври. 2018 г.`

-   Първо училище по ехокардиография. гр. София Въведение в ехокадиографската диагностика

`22-23. февруари. 2019 г.`

-   Второ училище по ехокардиография гр. София Ехографска оценка на вродени и придобити сърдечносъдови заболявания

`7-9. ноември. 2019 г.`

-   Научен симпозиум „Тахиаритмии и синкоп" 22-23. ноември.2019г. Трето училище по ехокардиография. гр. София „Нови ехографски методи в кардиологията"

`22-26.март.2021 г.`

-   Курс "Биостатистика с IBM SPSS Statistics for Windows, Version 22.0"

`март. 2020 г.`

-   English for academic purposes, Ирина Митърчева, дф; Департамент по езиково обучение (ДЕСО), МУ-Пловдив 

-   Езикови въпроси на научния и медицински текст; Департамент по езиково обучение (ДЕСО), МУ-Пловдив, Доц. Милиева, дф

`юни. 2021 г.` 

-   Интензивн специализиран курс „Академично писане, изработване на кохранови системни ревюта“ 
 Договор КП – 06-ДК1/6 от 29.03.2021 г. „COVID-19 HUB – Информация, иновации и имплементация на интегративни научни разработки“, финансиран по конкурс, свързан с пандемията от COVID-19, към Фонд „Научни изследвания“ – МОН. 

 `септември. 2021 г.`

-   Курс "Мащинно самоубочение" Machine Learning; СофтУни 

### Международни

`1-2. декември. 2017 г.`

-   Critical appraisal course, гр. София CPD

`27.март.2021 г.`

-   8th annual symposium "HTA assessment -- strategies for accelerated access" Institute for Rare Diseases

`10-15.октомври.2021 г.`

-   Оpen Medical Institute (OMI) Seminar “Economic Evaluation in Healthcare”

- 